### ISSUE TITLE
Custom mapping not working as expected

### ISSUE THREAD

**Issue by ketanchandak582** [play-swagger/play-swagger#3]
Hi, I am trying to using play-swagger to generate my spec. Some of my fields(both in query params or body are of java.util.UUID type), I have added the custom mapping spec as following:
```
---
- type: java\.util\.UUID
  specAsParameter:
    - type: string
      format: uuid
  specAsProperty:
    type: string
    format: uuid
 ```
 
 However, it is still generating an incorrect spec for property UUID fields like this:
 
 ```
      account_id:
        type: uuid
      user_id:
        type: uuid
 ```
 
 It should instead be 
 ```
       account_id:
        type: string
        format: uuid
      user_id:
        type: string
        format: uuid
 ```
 
 Am I not setting it up correctly? I also tried it directly in scala code:
 
 ```
 class UUIDTransformer extends OutputTransformer {

  def apply(json: JsValue): Try[JsValue] = {

    val transformUUID = (value: JsValue) => {
      value match {
        case obj: JsObject
            if (obj \ "type")
              .asOpt[String]
              .map(_.toLowerCase())
              .contains("uuid") =>
          Success(
            obj + ("type" -> JsString("string")) + ("format" -> JsString(
              "uuid"
            ))
          )
        case other => Success(other)
      }
    }

    json match {
      case obj: JsObject =>
        OutputTransformer.traverseTransformer(obj)(transformUUID)
      case arr: JsArray =>
        OutputTransformer.traverseTransformer(arr)(transformUUID)
      case other => Success(other)
    }

  }

  override def apply(obj: JsObject): Try[JsObject] =
    apply(obj: JsValue).map(_.as[JsObject])
}
```
And then using it while initializing the generator:

```
  private val domainPackage = "models"
  lazy val generator = SwaggerSpecGenerator(
    namingStrategy = NamingStrategy.SnakeCase,
    outputTransformers = Seq(new UUIDTransformer),
    domainNameSpaces = domainPackage
  )

```
Above did not work either.
 Also, if I wanted to use a case class but still override certain fields in the routes file, how would I do that? I can maybe make it work if that is possible

**Comment by phamtrinli** [comment]
Hi @ketanchandak582,
I faced something similar and for me using only uuid instead java.util.uuid did the trick. 
E.g. in the json format swagger-custom-mappings.json

`  {
    "type": "uuid",
    "specAsParameter": [
      {
        "type": "string",
        "format": "uuid"
      }
    ],
    "specAsProperty": {
      "type": "string",
      "format": "uuid"
    }
  }
`

**Comment by Javakky-pxv** [comment]
@ketanchandak582 
Can you provide a sample project or something that reproduces the above problem?

**Comment by Javakky-pxv** [comment]
@ketanchandak582 
Thank you very much. I will see if I can reproduce it on my end.
It will take some time, so if you are in a hurry, pull requests are welcome.

**Comment by funkrusher** [comment]
I have a similar issue with version 1.4.4 of play-swagger

Im using following "swagger-custom-mappings.json":
```
[{
  "type": "java\\.sql\\.Date",
  "specAsParameter": [{
    "type": "string",
    "format": "date"
  }],
  "specAsProperty": {
    "type": "string",
    "format": "date"
  }
}]
```
but nothing changes in the generated swagger.json. It looks like this:
```
"date_of_birth" : {
  "format" : "date",
  "type" : "java.sql.date",
  "x-nullable" : true
},
```

**Comment by funkrusher** [comment]
@ketanchandak582 

Hello ketanchandak582,

i had the same problem.

see: https://github.com/play-swagger/play-swagger/issues/35

i resolved it by using the latest published version of this plugin (1.4.4).

also see:
- https://github.com/play-swagger/play-swagger/issues/36

maybe this can help you too...

**Comment by ketanchandak582** [comment]
Hi @funkrusher, thanks for letting me know. I however am using the alternative setup(exposing the swagger gen as a endpoint)(https://github.com/play-swagger/play-swagger/blob/master/docs/AlternativeSetup.md) - so using play-swagger as a dependency and not a plugin, and I see it still uses iheart dependencies, so not sure how to make this work there

**Comment by funkrusher** [comment]
@ketanchandak582 the com.iheart dependency is the old github repository i think. The following should work for your use-case (library instead of plugin)

```
  "io.github.play-swagger" %% "play-swagger"          % "1.4.4",
```

**Comment by ketanchandak582** [comment]
Okay, the above import is working now, thanks! 

So, I have a file `conf/swagger-custom-mappings.yaml` with contents:
```
---
- type: java\.util\.UUID
  specAsParameter:
    - type: string
      format: uuid
  specAsProperty:
    type: string
    format: uuid
```
But I still see `Unknown Type: uuid` for UUID type fields
